service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

  environment:
    PRODUCTS: products
    STOCK: stock
    S3_BUCKET_NAME: ${self:custom.s3BucketName}
  
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "S3:ListBucket"
          Resource: 
            - "arn:aws:s3:::chg-import-service-dev"
        - Effect: "Allow"
          Action: "S3:*"
          Resource: 
            - "arn:aws:s3:::chg-import-service-dev/*"

package:
  exclude:
    - ./node_modules

custom:
  s3BucketName: chg-import-service-dev

functions:
  getProductsList:
    handler: src/product-service/functions/getProductsList.handler
    events:
      - http:
          path: products
          method: get
  getProductsById:
    handler: src/product-service/functions/getProductsById.handler
    events:
      - http:
          path: /products/{productId}
          method: get
  createProduct:
    handler: src/product-service/functions/createProduct.handler
    events:
      - http:
          path: /products
          method: post
  importProductsFile:
    handler: src/import-service/functions/importProductsFile.handler
    events:
      - httpApi:
          path: /import
          method: get
  importFileParser:
    handler: src/import-service/functions/importFileParser.handler
    events:
      - s3:
          bucket: ${self:custom.s3BucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true
