service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

  stage: dev
  region: us-east-1

  environment:
    PRODUCTS: products
    STOCK: stock

package:
  exclude:
    - ./node_modules

functions:
  getProductsList:
    handler: functions/getProductsList.handler
    events:
      - http:
          path: products
          method: get
  getProductsById:
    handler: functions/getProductsById.handler
    events:
      - http:
          path: /products/{productId}
          method: get
  createProduct:
    handler: functions/createProduct.handler
    events:
      - http:
          path: /products
          method: post
